### ISSUE TITLE
howto build this project?

### ISSUE THREAD

**Issue by domov0y** [gsimon75-stm32/scope#1]
Please add instruction how to build the project (or dependence list)

preprocess.awk - file not found. 
SDL.h -  package version?

**Comment by gsimon75** [comment]
Thanks for the feedback!
The .awk was indeed missing (forgot to add it before commit), now it's there, and I also added some notes on the build process.
I leave this issue open, so if there is any further thing missing, just leave a comment and I'll try to fix them.

**Comment by domov0y** [comment]
All ok. Build successfuly
